name: Android

on:
  push:
    branches:
      - master
      - fix-ci
  pull_request:
    paths:
      - '.github/workflows/main.yml'
      - 'src/**'
      - 'android/**'
      - 'MMKV/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build Android apk (release)
        run: |
          npm ci --legacy-peer-deps
          npm run build
          cd packages/devtools-plugin
          npm ci --legacy-peer-deps
          npm run build
          cd ../../example
          npm ci --legacy-peer-deps
          cd android
          ./gradlew assembleRelease
